apiVersion: my.api.group/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: int03012024
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: int03012024
  name: myappresource-sample
spec:
  # TODO(user): Add fields here
